### ISSUE TITLE
rpm build fails on RHEL 7.1 duplicate files in rpm

### ISSUE THREAD

**Issue by fang64** [metalefty/X11RDP-RH-Matic#7]
It seems under a vanilla RHEL 7.1 install there is an issue with duplicate files I suspect the RPM Spec file. 

These seem to be the problem...

RPM build errors:
    File listed twice: /etc/logrotate.d/xrdp
    File listed twice: /etc/pam.d/xrdp-sesman
    File listed twice: /etc/rc.d/init.d
    File listed twice: /etc/rc.d/init.d/xrdp
    File listed twice: /etc/sysconfig/xrdp
    File listed twice: /etc/xrdp
    File listed twice: /etc/xrdp/rsakeys.ini
    File listed twice: /etc/xrdp/sesman.ini
    File listed twice: /etc/xrdp/xrdp.ini
    File listed twice: /usr/share/man/man1/xrdp-dis.1.gz
    File listed twice: /usr/share/man/man5/sesman.ini.5.gz
    File listed twice: /usr/share/man/man5/xrdp.ini.5.gz
    File listed twice: /usr/share/man/man8/xrdp-chansrv.8.gz
    File listed twice: /usr/share/man/man8/xrdp-genkeymap.8.gz
    File listed twice: /usr/share/man/man8/xrdp-keygen.8.gz
    File listed twice: /usr/share/man/man8/xrdp-sesadmin.8.gz
    File listed twice: /usr/share/man/man8/xrdp-sesman.8.gz
    File listed twice: /usr/share/man/man8/xrdp-sesrun.8.gz
    File listed twice: /usr/share/man/man8/xrdp-sessvc.8.gz
    File listed twice: /usr/share/man/man8/xrdp.8.gz
    File listed twice: /usr/share/xrdp
    Installed (but unpackaged) file(s) found:
   /usr/lib/systemd/system/xrdp-sesman.service
   /usr/lib/systemd/system/xrdp.service

Not entirely sure why the systemd related files weren't grabbed I'm guessing they are not in the rpm at the moment? I imagine that doesn't cause the rpm to fail to build though...

I've attached the log here:
http://fpaste.org/203632/27435508/

**Comment by metalefty** [comment]
Probably I already fixed in develop branch. Can you try develop branch?

BTW, I'm not subscribing the ture RHEL.  Development is under CentOS.  They 're almost same but not identical.  Sorry for this tool is not well tested on the true RHEL.

**Comment by fang64** [comment]
metalefty, ah ok I'll give that a whirl here shortly, I did hack on the SPEC file trying to get it to compile, eventually did but hit another problem with nox11rdp seems it's traveling into a non-existent directory to compile xorg.

**Comment by fang64** [comment]
metalefty, well I am still seeing the duplicate file messages but they are being shown as warnings. It does create the packages now. for xrdp at least. It does appear to still be traveling into the wrong path for compiling xorg however that's a separate issue entirely. 

Here is the updated log:
http://ur1.ca/jzt6j

**Comment by metalefty** [comment]
I've confirmed your issue but it is another issue.  I made a new issue #9.  I will look at it and fix in a few days.
